name: build-artifacts
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build/
    steps:
      - uses: actions/checkout@v2
      - run: ./build-gh-artifact.sh test-js ${{ secrets.GITHUB_TOKEN }}
      - run: mv out/* ../public/js
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/
